- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`care_site`'
  columns:
    care_site_id: BIGINT
    care_site_name: STRING
    place_of_service_concept_id: BIGINT
    location_id: BIGINT
    care_site_source_value: STRING
    place_of_service_source_value: STRING
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`condition_era`'
  columns:
    condition_era_id: BIGINT
    person_id: BIGINT
    condition_concept_id: BIGINT
    condition_era_start_date: DATE
    condition_era_end_date: DATE
    condition_occurrence_count: INT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`condition_occurrence`'
  columns:
    condition_occurrence_id: BIGINT
    person_id: BIGINT
    condition_concept_id: BIGINT
    condition_start_date: DATE
    condition_start_datetime: TIMESTAMP
    condition_end_date: DATE
    condition_end_datetime: TIMESTAMP
    condition_type_concept_id: BIGINT
    condition_status_concept_id: BIGINT
    stop_reason: STRING
    provider_id: BIGINT
    visit_occurrence_id: BIGINT
    visit_detail_id: BIGINT
    condition_source_value: STRING
    condition_source_concept_id: BIGINT
    condition_status_source_value: STRING
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`death`'
  columns:
    person_id: BIGINT
    death_date: DATE
    death_datetime: TIMESTAMP
    death_type_concept_id: BIGINT
    cause_concept_id: BIGINT
    cause_source_value: STRING
    cause_source_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`device_exposure`'
  columns:
    device_exposure_id: BIGINT
    person_id: BIGINT
    device_concept_id: BIGINT
    device_exposure_start_date: DATE
    device_exposure_start_datetime: TIMESTAMP
    device_exposure_end_date: DATE
    device_exposure_end_datetime: TIMESTAMP
    device_type_concept_id: BIGINT
    unique_device_id: STRING
    production_id: STRING
    quantity: INT
    provider_id: BIGINT
    visit_occurrence_id: BIGINT
    visit_detail_id: BIGINT
    device_source_value: STRING
    device_source_concept_id: BIGINT
    unit_concept_id: BIGINT
    unit_source_value: STRING
    unit_source_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`drug_era`'
  columns:
    drug_era_id: BIGINT
    person_id: BIGINT
    drug_concept_id: BIGINT
    drug_era_start_date: DATE
    drug_era_end_date: DATE
    drug_exposure_count: INT
    gap_days: INT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`drug_exposure`'
  columns:
    drug_exposure_id: BIGINT
    person_id: BIGINT
    drug_concept_id: BIGINT
    drug_exposure_start_date: DATE
    drug_exposure_start_datetime: TIMESTAMP
    drug_exposure_end_date: DATE
    drug_exposure_end_datetime: TIMESTAMP
    verbatim_end_date: DATE
    drug_type_concept_id: BIGINT
    stop_reason: STRING
    refills: INT
    quantity: DOUBLE
    days_supply: INT
    sig: STRING
    route_concept_id: BIGINT
    lot_number: STRING
    provider_id: BIGINT
    visit_occurrence_id: BIGINT
    visit_detail_id: BIGINT
    drug_source_value: STRING
    drug_source_concept_id: BIGINT
    route_source_value: STRING
    dose_unit_source_value: STRING
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`location`'
  columns:
    location_id: BIGINT
    address_1: STRING
    address_2: STRING
    city: STRING
    state: STRING
    zip: STRING
    county: STRING
    location_source_value: STRING
    country_concept_id: BIGINT
    country_source_value: STRING
    latitude: DOUBLE
    longitude: DOUBLE
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`measurement`'
  columns:
    measurement_id: BIGINT
    person_id: BIGINT
    measurement_concept_id: BIGINT
    measurement_date: TIMESTAMP
    measurement_datetime: TIMESTAMP
    measurement_time: TIMESTAMP
    measurement_type_concept_id: BIGINT
    operator_concept_id: BIGINT
    value_as_number: DOUBLE
    value_as_concept_id: BIGINT
    unit_concept_id: BIGINT
    range_low: INT
    range_high: INT
    provider_id: BIGINT
    visit_occurrence_id: BIGINT
    visit_detail_id: BIGINT
    measurement_source_value: STRING
    measurement_source_concept_id: BIGINT
    unit_source_value: STRING
    unit_source_concept_id: BIGINT
    value_source_value: STRING
    meas_event_field_concept_id: BIGINT
    measurement_event_id: STRING
    unique_key: STRING
    datasource: STRING
    updated_at: TIMESTAMP
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`note`'
  columns:
    note_id: BIGINT
    person_id: BIGINT
    note_date: DATE
    note_datetime: TIMESTAMP
    note_type_concept_id: BIGINT
    note_class_concept_id: BIGINT
    note_title: STRING
    note_text: STRING
    encoding_concept_id: BIGINT
    language_concept_id: BIGINT
    provider_id: BIGINT
    visit_occurrence_id: BIGINT
    visit_detail_id: BIGINT
    note_source_value: STRING
    note_event_id: BIGINT
    note_event_field_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`observation`'
  columns:
    observation_id: BIGINT
    person_id: BIGINT
    observation_concept_id: BIGINT
    observation_date: DATE
    observation_datetime: TIMESTAMP
    observation_type_concept_id: BIGINT
    value_as_number: DOUBLE
    value_as_string: STRING
    value_as_concept_id: BIGINT
    qualifier_concept_id: BIGINT
    unit_concept_id: BIGINT
    provider_id: BIGINT
    visit_occurrence_id: BIGINT
    visit_detail_id: BIGINT
    observation_source_value: STRING
    observation_source_concept_id: BIGINT
    unit_source_value: STRING
    qualifier_source_value: STRING
    value_source_value: STRING
    observation_event_id: STRING
    obs_event_field_concept_id: BIGINT
    unique_key: STRING
    datasource: STRING
    updated_at: TIMESTAMP
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`observation_period`'
  columns:
    observation_period_id: BIGINT
    person_id: BIGINT
    observation_period_start_date: DATE
    observation_period_end_date: DATE
    period_type_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`payer_plan_period`'
  columns:
    payer_plan_period_id: BIGINT
    person_id: BIGINT
    payer_plan_period_start_date: TIMESTAMP
    payer_plan_period_end_date: TIMESTAMP
    payer_concept_id: BIGINT
    payer_source_value: STRING
    payer_source_concept_id: BIGINT
    plan_concept_id: BIGINT
    plan_source_value: STRING
    plan_source_concept_id: BIGINT
    sponsor_concept_id: BIGINT
    sponsor_source_value: STRING
    sponsor_source_concept_id: BIGINT
    family_source_value: STRING
    stop_reason_concept_id: BIGINT
    stop_reason_source_value: STRING
    stop_reason_source_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`person`'
  columns:
    person_id: BIGINT
    gender_concept_id: BIGINT
    year_of_birth: INT
    month_of_birth: INT
    day_of_birth: INT
    birth_datetime: TIMESTAMP
    race_concept_id: BIGINT
    ethnicity_concept_id: BIGINT
    location_id: BIGINT
    provider_id: BIGINT
    care_site_id: BIGINT
    person_source_value: STRING
    gender_source_value: STRING
    gender_source_concept_id: BIGINT
    race_source_value: STRING
    race_source_concept_id: BIGINT
    ethnicity_source_value: STRING
    ethnicity_source_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`procedure_occurrence`'
  columns:
    procedure_occurrence_id: BIGINT
    person_id: BIGINT
    procedure_concept_id: BIGINT
    procedure_date: DATE
    procedure_datetime: TIMESTAMP
    procedure_end_date: DATE
    procedure_end_datetime: TIMESTAMP
    procedure_type_concept_id: BIGINT
    modifier_concept_id: BIGINT
    quantity: INT
    provider_id: BIGINT
    visit_occurrence_id: BIGINT
    visit_detail_id: BIGINT
    procedure_source_value: STRING
    procedure_source_concept_id: BIGINT
    modifier_source_value: STRING
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`provider`'
  columns:
    provider_id: BIGINT
    provider_name: STRING
    npi: STRING
    dea: STRING
    specialty_concept_id: BIGINT
    care_site_id: BIGINT
    year_of_birth: INT
    gender_concept_id: BIGINT
    provider_source_value: STRING
    specialty_source_value: STRING
    specialty_source_concept_id: BIGINT
    gender_source_value: STRING
    gender_source_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`visit_detail`'
  columns:
    visit_detail_id: BIGINT
    person_id: BIGINT
    visit_detail_concept_id: BIGINT
    visit_detail_start_date: DATE
    visit_detail_start_datetime: TIMESTAMP
    visit_detail_end_date: DATE
    visit_detail_end_datetime: TIMESTAMP
    visit_detail_type_concept_id: BIGINT
    provider_id: BIGINT
    care_site_id: BIGINT
    visit_detail_source_value: STRING
    visit_detail_source_concept_id: BIGINT
    admitted_from_concept_id: BIGINT
    admitted_from_source_value: STRING
    discharged_to_source_value: STRING
    discharged_to_concept_id: BIGINT
    preceding_visit_detail_id: BIGINT
    parent_visit_detail_id: BIGINT
    visit_occurrence_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`visit_occurrence`'
  columns:
    visit_occurrence_id: BIGINT
    person_id: BIGINT
    visit_concept_id: BIGINT
    visit_start_date: DATE
    visit_start_datetime: TIMESTAMP
    visit_end_date: DATE
    visit_end_datetime: TIMESTAMP
    visit_type_concept_id: BIGINT
    provider_id: BIGINT
    care_site_id: BIGINT
    visit_source_value: STRING
    visit_source_concept_id: BIGINT
    admitted_from_concept_id: BIGINT
    admitted_from_source_value: STRING
    discharged_to_concept_id: BIGINT
    discharged_to_source_value: STRING
    preceding_visit_occurrence_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
