- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`person`'
  columns:
    person_id: BIGINT
    gender_concept_id: BIGINT
    year_of_birth: INT
    month_of_birth: INT
    day_of_birth: INT
    birth_datetime: TIMESTAMP
    race_concept_id: BIGINT
    ethnicity_concept_id: BIGINT
    location_id: BIGINT
    provider_id: BIGINT
    care_site_id: BIGINT
    person_source_value: STRING
    gender_source_value: STRING
    gender_source_concept_id: BIGINT
    race_source_value: STRING
    race_source_concept_id: BIGINT
    ethnicity_source_value: STRING
    ethnicity_source_concept_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
- name: '`dbw-lsc-uks-datadev-dlz-01`.`lth_omop`.`visit_occurrence`'
  columns:
    visit_occurrence_id: BIGINT
    person_id: BIGINT
    visit_concept_id: BIGINT
    visit_start_date: DATE
    visit_start_datetime: TIMESTAMP
    visit_end_date: DATE
    visit_end_datetime: TIMESTAMP
    visit_type_concept_id: BIGINT
    provider_id: BIGINT
    care_site_id: BIGINT
    visit_source_value: STRING
    visit_source_concept_id: BIGINT
    admitted_from_concept_id: BIGINT
    admitted_from_source_value: STRING
    discharged_to_concept_id: BIGINT
    discharged_to_source_value: STRING
    preceding_visit_occurrence_id: BIGINT
    source_system: STRING
    inserted_process_instance_id: STRING
    updated_process_instance_id: STRING
    inserted_process_queue_id: STRING
    updated_process_queue_id: STRING
    inserted_date_time: TIMESTAMP
    updated_date_time: TIMESTAMP
